### ISSUE TITLE
select country based on search country in textfield

### ISSUE THREAD

**Issue by Mahipal-codzgarage** [ArthurGuibert/FSInteractiveMap#10]
if i type counrty name in textfield, and search that time highlight serch country name...
is it possible ?

**Comment by ArthurGuibert** [comment]
You can use the enumerateLayersUsingBlock method and select the layer with an identifier that matches the search.

**Comment by Mahipal-codzgarage** [comment]
Thanks for reply, but i am new in iOS Development.
So, can you please give me a code example. so, i can implement in my project.
